version: "3.5"

networks:
  grav:

services:
  ingress:
    networks:
      - grav
      
  grav:
    image: dsavell/grav:admin-1.6.11
    deploy:
      mode: global
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        # TODO: Currently / takes you to grav. Make that optional for any service?
        - traefik.frontend.rule=HostRegexp:grav.{domain:.+},{domain:.+}
        - traefik.frontend.priority=1
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=ingress
        - traefik.docker.network=${STACK_NAME:-technocore}_grav
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - grav
    volumes:
      - grav-backup:/var/www/grav/backup 
      - grav-logs:/var/www/grav/logs 
      - grav-user:/var/www/grav/user 
volumes: 
  grav-backup:
  grav-logs:
  grav-user:
